name: Build and Push Docker Image

on:
  schedule:
    - cron: "0 0 * * *"  # 每天检查一次 Endava cats 的 release 页面
  workflow_dispatch:  # 手动触发
  repository_dispatch:
    types: [cats_release]

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release info from CATS
        id: get_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/Endava/cats/releases/latest)
          tag_name=$(echo "$latest_release" | jq -r '.tag_name')
          if [[ "$tag_name" == "null" ]]; then
            echo "No releases found."
            exit 1
          fi
          echo "Latest release: $tag_name"
          echo "TAG=$tag_name" >> $GITHUB_ENV  # 使用 Environment Files 代替 set-output

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download latest release
        run: |
          CATS_URL="https://github.com/Endava/cats/releases/download/${{ env.TAG }}/cats_linux_amd64_${{ env.TAG }}.tar.gz"
          curl -L -o cats.tar.gz "$CATS_URL"
      
      - name: Extract downloaded tar
        run: tar -xzf cats.tar.gz

      - name: Build Docker Image
        run: |
          docker build -t highkay/cats:${{ env.TAG }} -t highkay/cats:latest .

      - name: Push Docker Image
        run: |
          docker push highkay/cats:${{ env.TAG }}
          docker push highkay/cats:latest
