name: Build and Push Docker Image

on:
  # 监听 Endava/cats 项目的新版本发布
  schedule:
    - cron: "0 0 * * *" # 每天检查一次 Endava cats 的 release 页面
  workflow_dispatch: # 手动触发
  repository_dispatch:
    types: [cats_release]

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest release info from CATS
        id: get_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/Endava/cats/releases/latest)
          tag_name=$(echo "$latest_release" | jq -r '.tag_name')
          if [[ "$tag_name" == "null" ]]; then
            echo "No releases found."
            exit 1
          fi
          echo "Latest release: $tag_name"
          echo "::set-output name=tag::$tag_name"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download latest release
        run: |
          TAG=${{ steps.get_release.outputs.tag }}
          CATS_URL="https://github.com/Endava/cats/releases/download/${TAG}/cats_linux_amd64_${TAG}.tar.gz"
          curl -L -o cats.tar.gz "$CATS_URL"
      
      - name: Extract downloaded tar
        run: tar -xzf cats.tar.gz

      - name: Build Docker Image
        run: |
          TAG=${{ steps.get_release.outputs.tag }}
          docker build -t highkay/cats:$TAG -t highkay/cats:latest .

      - name: Push Docker Image
        run: |
          TAG=${{ steps.get_release.outputs.tag }}
          docker push highkay/cats:$TAG
          docker push highkay/cats:latest